### ISSUE TITLE
[Feature] Add option to focus next opened buffer is no visible buffers.

### ISSUE THREAD

**Issue by towry** [roobert/bufferline-cycle-windowless.nvim#1]
For example we have three buffers opened in three split windows, the current behavior is if we use this plugin provided command to switch buffers, nothing happened, but it could be better to focus the next opened buffer.

**Comment by roobert** [comment]
Hi @towry.

Thank you for opening an issue.

If you have three splits open (i.e: 3 windows with 3 open buffers) then, with the way the neovim window-buffers model works, you would use `<C-w>h`, `<C-w>j`, `<C-w>k` and `<C-w>l` to move between the windows.

I recommend remapping these to `<C-h>`, `<C-j>`, `<C-k>` and `<C-l>` for easier window movement.

This plugin deals with cycling of buffers within an open window, rather than movement between windows. I'm not sure if it would be possible to implement something in the way you suggest with how the Neovim window and buffer management model works.

Hope this helps!
